Node-study-programmers/travelevart-FrontEnd

- src/app/not-found.tsx
- [0] 기능 추가
> Issue Numbe
- 요약
- notfound page 생성
- 바뀐 부분
- [0] No
-
> [Feature] : notfound page - suhyuk

- src/app/error.tsx
> Issue Numbe
- 요약
- 메인 페이지에서 오류 발생시 페이지 이동 불가능한 오류 수정
- 도메인 주소를 기준으로 메인 페이지 판별
- API 연동 이후 에러별 상세 렌더링 예정
- 충돌로 인한 재PR
> [Fix] : error page - choongnyeong

- src/app/(main)/page.tsx
- src/app/ui/common/DropDown.tsx
- src/app/ui/common/Navbar.tsx
- src/app/ui/common/Select.tsx
- tailwind.config.ts
> Issue Numbe
- 요약
- select ui 생성 완료 
- 바뀐 부분
- [x ] No
-
> [Feature]:Select UI - suhyuk

- src/app/ui/common/carousel/Carousel.tsx
- src/app/ui/common/carousel/CarouselContent.tsx
- tailwind.config.ts
> Issue Numbe
- 요약
- 캐러셀 컴포넌트 생성
- api에 따라 확장해 사용할 수 있도록 제목, 내용 props로 사용
- 슬라이드 버튼용 config 추가
- 케러셀, 각 배너 의존도 낮추기 위해 컴포넌트로 분리
- ui/common/carousel
- Carousel.tsx
- CarouselContent.tsx
- api 연동, 컨테이너 적용 이후 반응형 스타일 적용 예정
- api 연동 이후 각 배너에 링크 적용 예정
> [Design] : make carousel - choongyeong

- src/app/auth/login/page.tsx
- src/app/auth/register/page.tsx
- src/lib/authOptions.ts
- src/stories/Page.tsx
> Issue Numbe
- 요약
- pass word 확인 추가 , 로그인 페이지 타입 에러 수정
- 바뀐 부분
-
> [Feature]:passwordvalidation추가, registerpage css 수정-suhyuk

- src/lib/authOptions.ts
> Issue Numbe
- 요약
- 소셜 로그인 api 오타 수정
-
> [Fix] : api 오타 수정 - choongnyeong

- src/lib/authOptions.ts
- src/middleware.ts
- src/util/getCurrentUser.ts
> Issue Numbe
- 요약
- login redirect middleware 작성
- login 시 에 또는 session 이 있을시에 /auth 페이지로 진입 못하게 함
- 바뀐 부분
-
> [Feature]:LoginRedirect-suhyuk

- src/app/community/page.tsx
- src/app/ui/common/CategoryTabs.tsx
- src/app/ui/common/Drawer.tsx
- src/app/ui/common/Header.tsx
- src/app/ui/common/Navbar.tsx
> Issue Numbe
- 요약
- community container ui 제작
- navbar ui 버그 수정 
- 바뀐 부분
-
> [Style]:community container ui-suhyuk

- src/app/community/page.tsx
- src/app/hooks/community/usePopularPost.ts
- src/app/hooks/community/usePostsInfinitiQuery.ts
- src/app/hooks/useDebounce.ts
- src/app/hooks/useIntersectionObserver.ts
- src/app/ui/common/Header.tsx
- src/app/ui/community/CommunityPopularPost.tsx
- src/app/ui/community/CommunityPostContainer.tsx
- src/constant/index.ts
- src/lib/types.ts
> Issue Numbe
- 요약
- 커뮤니티 infinityQuery 연동
- 인기게시물 react query 연동
- header 배경색 추가
- debounce util 함수 추가
- observer 추가
- 
- 바뀐 부분
-
> [Feature]:InfinityQuerypopularhook-suhyuk

- next.config.mjs
- package-lock.json
- package.json
- src/app/community/page.tsx
- src/app/globals.css
- src/app/hooks/community/usePopularPost.ts
- src/app/hooks/community/usePostsInfinitiQuery.ts
- src/app/ui/common/CategoryTabs.tsx
- src/app/ui/common/Footer.tsx
- src/app/ui/common/Header.tsx
- src/app/ui/common/Navbar.tsx
- src/app/ui/community/CommunityFreePost.tsx
- src/app/ui/community/CommunityPopularPost.tsx
- src/app/ui/community/CommunityTravelPost.tsx
- src/app/ui/community/skeleton/CommunityPostSkeleton.tsx
- src/lib/api.ts
- tailwind.config.ts
> Issue Numbe
- 요약
- 자유게시판 ui 부분 제작
- 검색 기능 및 에러 해결
- skeleton 구현
- isFetchingNextPage 으로 다시 패치시 스켈레톤 보이도록 함
- 바뀐 부분
- date-fns 설치 함 -> npm ci 필요
- nextconfig에 이미지 불러오기위한 extend 작성함
- categorytabs에 반응형으로 margin 주도록 추가함
> [Style]:FreePostUI-suhyuk

- next.config.mjs
- src/app/community/[board]/[id]/page.tsx
- src/app/community/[board]/page.tsx
- src/app/hooks/community/useDetailPost.ts
- src/app/hooks/community/useGetComments.ts
- src/app/hooks/community/useLikePost.ts
- src/app/hooks/community/usePostsInfinitiQuery.ts
- src/app/ui/common/CategoryTabs.tsx
- src/app/ui/common/DragAndDrop.tsx
- src/app/ui/common/Navbar.tsx
- src/app/ui/common/PageContainer.tsx
- src/app/ui/community/CommentForm.tsx
- src/app/ui/community/CommunityFreeDetailPage.tsx
- src/app/ui/community/CommunityFreePost.tsx
- src/app/ui/community/CommunityPage.tsx
- src/app/ui/community/CommunityPopularPost.tsx
- src/app/ui/community/CommunityTravelPost.tsx
- src/app/ui/community/PopularPosts.tsx
- src/app/ui/community/PostBottoms.tsx
- src/app/ui/community/skeleton/CommunityPostSkeleton.tsx
- src/middleware.ts
- src/util/convertTimeAgo.ts
- tailwind.config.ts
> Issue Numbe
- 요약
- 바뀐 부분
- 자유게시판 ui 기능 마무리
- 댓글 추가 삭제기능
- 게시물 좋아요 유저 정보 이동기능
-
> [Feature]:FreeboardFinish-suhyuk

- next.config.mjs
- src/app/hooks/searchTrip/useAddReview.ts
- src/app/hooks/searchTrip/useGetDetailTravelPage.ts
- src/app/hooks/searchTrip/useReviewInfinitiQuery.ts
- src/app/mypage/[userId]/page.tsx
- src/app/mypage/edit-profile/page.tsx
- src/app/mypage/page.tsx
- src/app/search-trip/[id]/page.tsx
- src/app/ui/common/CategoryTabs.tsx
- src/app/ui/common/Drawer.tsx
- src/app/ui/community/DetailContents.tsx
- src/app/ui/community/ReviewContainer.tsx
- src/app/ui/travelDestination/IconButtons.tsx
- src/app/ui/travelDestination/ReviewWithStar.tsx
- src/app/ui/travelDestination/StarInput.tsx
- src/app/ui/travelDestination/StarRating.tsx
- src/app/ui/travelDestination/skeleton/DetailPageSkeleton.tsx
- src/util/getCurrentUser.ts
> Issue Numbe
- 요약
- travel detail페이지 ui 
- 별점 리뷰 기능 무한 스크롤 기능
- 바뀐 부분
-
> [Feature/UI]:TravelDetailPage ui,reviewFeature,starReview-suhyuk

- next.config.mjs
- src/app/hooks/searchTrip/useBannerContents.ts
- src/app/hooks/searchTrip/useGetDetailFestival.ts
- src/app/layout.tsx
- src/app/search-trip/festival/[id]/page.tsx
- src/app/search-trip/page.tsx
- src/app/ui/common/PageContainer.tsx
- src/app/ui/common/carousel/Carousel.tsx
- src/app/ui/common/carousel/CarouselContent.tsx
- src/app/ui/common/carousel/CarouselSkeleton.tsx
- src/app/ui/travelDestination/AllTravelDestination.tsx
- src/lib/types.ts
- tailwind.config.ts
> Issue Numbe
- 요약
- 여행페이지 메인 배너 행사부분 연결
- 행사 자세히보기시 detailpage 구현
- 바뀐 부분
-
> [Style]:FestivalBanner,Detail-suhyuk

- src/app/hooks/useIntersectionObserver.ts
- src/app/search-trip/page.tsx
- src/app/ui/common/Header.tsx
- src/app/ui/common/Navbar.tsx
- src/app/ui/common/Select.tsx
> Issue Numbe
- 요약
- travel searchbar ui 수정 
- navbar 여러번 클릭해야 이동하는 버그 수정
- 바뀐 부분
-
> [Style]:searchbar ui-suhyuk

- src/app/travel-route/setup/page.tsx
- src/app/ui/common/travelRoute/TravelRouteSetUpForm.tsx
- src/redux/slices/travelRouteSlice.ts
> Issue Numbe
- 요약
- travelrout setup 페이지 디자인
- 초기 옵션에 교통수단 추가
-
> [Feature] Setup Design & add transport option - choongnyeong

- package-lock.json
- package.json
- src/app/hooks/useProfile.ts
- src/app/layout.tsx
- src/app/search-trip/festival/[id]/page.tsx
- src/app/ui/common/FeedbackForm.tsx
- src/app/ui/travelDestination/AllTravelDestination.tsx
- src/app/ui/travelDestination/IconButtons.tsx
- src/app/ui/travelDestination/ReviewWithStar.tsx
- src/lib/api.ts
> Issue Numbe
- alert 들 toast로 수정
- 바뀐 부분
-
> alert들 toast로 수정

- src/app/hooks/recommendTrip/useSaveRecommendTrip.ts
- src/app/hooks/searchTrip/useGetDetailTravelPage.ts
- src/app/ui/common/recommendTrip/RecommendTripDetailModal.tsx
- src/app/ui/common/recommendTrip/RecommendTripSchedule.tsx
- src/app/ui/common/travelRoute/TravelRouteSetUpForm.tsx
- src/app/ui/travelDestination/NaverMap.tsx
- src/app/ui/travelDestination/TravelRegionBanner.tsx
- src/lib/types.ts
- src/redux/slices/recommendTripSlice.ts
> Issue Numbe
- 요약
- 여행지 추천 구현 완료
-
> [Feature] : recommed trip - choongnyeong

- src/app/hooks/searchTrip/useGetCartTravelDestination.ts
- src/app/ui/common/recommendTrip/RecommendTripSchedule.tsx
- src/app/ui/travelDestination/AllTravelDestination.tsx
- src/app/ui/travelDestination/IconButtons.tsx
- src/app/ui/travelDestination/NaverMap.tsx
- src/lib/api.ts
> Issue Numbe
- 요약
- 토큰 만료시 발생하는 배열 오류 수정
-
> [Fix]: AccessToken - choongnyeong

- next.config.mjs
- src/app/hooks/recommendTrip/useSaveRecommendTrip.ts
- src/app/hooks/searchTrip/useGetCartTravelDestination.ts
- src/app/layout.tsx
- src/app/ui/common/recommendTrip/RecommendTripSchedule.tsx
- src/app/ui/common/recommendTrip/RecommendTripSetupForm.tsx
- src/app/ui/common/travelRoute/TravelRouteSetUpForm.tsx
> [Fix] : Fix/ErrorHandleing

- src/app/hooks/searchTrip/useGetCartTravelDestination.ts
- src/app/ui/travelDestination/AllTravelDestination.tsx
- src/app/ui/travelDestination/IconButtons.tsx
> Issue Numbe
- 요약
- 찜하기 에러 수정
-
> [Fix]: Cart

- src/middleware.ts
> Issue Numbe
- 요약
- 카카오 리다이렉트 오류 수정
-
> fix: kakao redirect

- src/middleware.ts
> Fix kakaoLogin

- src/app/(main)/page.tsx
- src/app/ui/common/recommendTrip/RecommendTripSchedule.tsx
- src/app/ui/common/travelRoute/TravelRouteSetUpForm.tsx
- src/middleware.ts
> Fix: video error

- src/app/ui/common/recommendTrip/RecommendTripSchedule.tsx
> Issue Numbe
- 요약
- 여행지 추천 시 토큰 만료될 경우 발생하는 타입 에러 수정
-
> Fix: 토큰 만료시 문법 오류 수정 : 충녕

- src/app/ui/common/recommendTrip/RecommendTripSetupForm.tsx
> Issue Numbe
- 요약
- 여행지 추천 타입 에러 수정
-
> Fix: 여행지 추천 타입 에러 수정
